### ISSUE TITLE
Build environment and IE compatibility 

### ISSUE THREAD

**Issue by kelvinau** [Adrianotiger/web-esheep#3]
What is your build environment? For example, there is esheep.min.js but I don't see any reference to the tools you used to build it. It may be better to use npm.

esheep.js is using ES6 class syntax, which is not supported in IE. The script is unable to be loaded. Either rewrite it or add Babel?

**Comment by Adrianotiger** [comment]
To be honest I used an old editor: AptanaStudio3 - because it was possible to edit the server files.
I am trying NetBeans now that is nice if you are coding PHP, Javascript directly on the server.

I know that IE is not able to load hte script. But is present only in Windows 7 and Windows XP. Maybe you can check if eSheep is present in the script (var es; if(eSheep) es=new eSheep();). 

But I intentionally wrote the code with classes, because it is similar to the C# project for Windows 8/10.

Edit: I am not really a web developer, I am a C++ developer... It was more a personal project. I am afraid to learn the npm package :P heheh But probably I have to do it, if I want a faster script.

**Comment by kelvinau** [comment]
npm package can be quite easy (and yarn is even easier!). This is a great project and I love how cute the sheep is! I have created a pull request for fixing these issues #4 .

**Comment by Adrianotiger** [comment]
I will try to learn it  :) 
Can you put the build environment files in a folder? Maybe there will be other environments in the future.

**Comment by kelvinau** [comment]
Sure. I just pushed a new commit to move gulpfile.js to the folder build

**Comment by kelvinau** [comment]
Close to issue because PR #4 is merged.
