### ISSUE TITLE
Remove external dependencies and make the library stand-alone

### ISSUE THREAD

**Issue by kelvinau** [Adrianotiger/web-esheep#5]
Two items I suggest on making it stand-alone:
- Remove use of external animation file (http://esheep.petrucci.ch/script/animation.php), because this is 
1. Not working with websites using https by default when requesting file with http
2. Vulnerable to attack as if the external file is maliciously modified, the library will be using that

- Remove popover on clicking
It's unnecessary to self-promote a website as it’s an open-source project and people are contributing on it together.

**Comment by Adrianotiger** [comment]
Hi Kelvy,
I will check it and find a solution. I have now a new server and the possibility to have https.

The problem was the cross-domain scripting. Using a php script I was able to give access to every domain including the headers:
``
header('Content-Disposition: inline; filename="animation.xml"');
header('Access-Control-Allow-Origin: *');
``
But would it be a solution to move it on a https server? Or host the xml on github (probably this will not work because the server does not give the access to other domains).

The idea on the popover was to give credits to the user who generated the animation, not the the website itself :P I will change a little bit the design of the popup and give the possibility to remove it over the animation.

I am also check if I can create a subfolder with all animations, so everyone can upload the xml on GitHub instead of upload them on my server.

I can do a lot on the web-based eSheep as I don't have the certificate to compile the C# project anymore.

**Comment by Adrianotiger** [comment]
- removed external links to my webpage and replaced it with the github webpage
- used https for external files
- added possibility to remove popup when creating the sheep
- added possibility to change pet during execution
- popup title and description have now the contents of the animation and not application

Can you check if I built it correctly? My script is 30kb, once compiled with .min.js it is 80kb! I think this is not the idea of minimizing the size of a script...

**Comment by kelvinau** [comment]
Moving to a https server will be better and of course you can set "Access-Control-Allow-Origin: *", given that it's just for a xml file I think there's not much any security concern. That can resolve the issue. But still, some users, like me, don't want to rely on external resources because of various reasons. One solution will be adding an option to overwrite the animationFile. Then people can download a xml and uses it locally, and simply just use the default https://adrianotiger.github.io/web-esheep/pets/original.xml.

Thanks for the option on the popup! I think this is a good solution.

**Comment by kelvinau** [comment]
It actually makes sense that the size increases after being compiled, because besides minimizing, the code is also converted into ES2015 syntax in order to solve issue #3. Our source code is written in ES6 format with class structure, IE does not support that and we use Babel to convert ES6 to ES2015 for cross-browser compatibility. ES2015's way of defining class is lengthy and so the line of codes increases.
